#!/bin/sh
# Enable ASYNC_COMMIT for Rockchip BSP kernel > 4.4

type modetest >/dev/null 2>/dev/null || exit 0

for p in $(modetest|grep "^Planes:" -A 9999|grep -o "^[0-9]*");
do
	modetest -M rockchip -aw $p:ASYNC_COMMIT:1 >/dev/null 2>/dev/null
done
