#!/bin/sh
#

lunch_start()
{
	echo "Now we are ready to start your first application" > /dev/kmsg
}

lunch_stop()
{
	echo "All applications have been stopped"
}

case "$1" in
	start)
		lunch_start
		;;
	stop)
		lunch_stop
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
