################################################################################
#
# rkpartybox
#
################################################################################

RKPARTYBOX_SITE = $(TOPDIR)/../app/rkpartybox
RKPARTYBOX_SITE_METHOD = local

RKPARTYBOX_LICENSE = ROCKCHIP
RKPARTYBOX_LICENSE_FILES = LICENSE

ifeq ($(BR2_PACKAGE_RK3308_CORE_BOARD),y)
RKPARTYBOX_CONF_OPTS += -DRK3308_PBOX_CORE_BOARD=TRUE
else
RKPARTYBOX_DEPENDENCIES += wpa_supplicant bluez5_utils
endif

ifeq ($(BR2_PACKAGE_PBOX_LCD_DISPLAY),y)
RKPARTYBOX_CONF_OPTS += -DLV_USE_DEMO_MUSIC=1
RKPARTYBOX_DEPENDENCIES += libdrm lvgl lv_drivers
endif

ifeq ($(BR2_PACKAGE_PBOX_LED_EFFECT),y)
RKPARTYBOX_CONF_OPTS += -DENABLE_RK_LED_EFFECT=TRUE
endif

ifeq ($(BR2_PACKAGE_ONCHIP_MIC),y)
RKPARTYBOX_CONF_OPTS += -DENABLE_MIC=TRUE
RKPARTYBOX_CONF_OPTS += -DMICPHONE_NUM=$(BR2_PACKAGE_MIC_NUM)
endif

ifeq ($(BR2_PACKAGE_RKCHIP_SARADC),y)
RKPARTYBOX_CONF_OPTS += -DENABLE_RKCHIP_SARADC=TRUE
endif

define RKPARTYBOX_POST_INSTALL_TO_TARGET
	$(INSTALL) -D -m 0755 $(@D)/lib64/lib* $(TARGET_DIR)/usr/lib/
endef
#RKPARTYBOX_POST_INSTALL_TARGET_HOOKS += RKPARTYBOX_POST_INSTALL_TO_TARGET
$(info RKPARTYBOX_CONF_OPTS is $(RKPARTYBOX_CONF_OPTS))
$(eval $(cmake-package))
