DBSERVER_SITE = $(TOPDIR)/../app/dbserver
DBSERVER_SITE_METHOD = local

DBSERVER_DEPENDENCIES = libgdbus librkdb

ifeq ($(BR2_PACKAGE_DBSERVER_SANITIZER_DYNAMIC), y)
DBSERVER_CONF_OPTS += -DSANITIZER_DYNAMIC=ON
else

ifeq ($(BR2_PACKAGE_DBSERVER_SANITIZER_STATIC), y)
DBSERVER_CONF_OPTS += -DSANITIZER_STATIC=ON
endif
endif

ifeq ($(BR2_PACKAGE_DBSERVER_MINILOGGER), y)
    DBSERVER_CONF_OPTS += -DENABLE_MINILOGGER=ON
    DBSERVER_DEPENDENCIES += minilogger
else
    DBSERVER_CONF_OPTS += -DENABLE_MINILOGGER=OFF
endif

$(eval $(cmake-package))
