#!/bin/sh
#
# Start Rockchip recovery...
#

case "$1" in
  start)
		echo "starting recovery... "
	  	touch /dev/.coldboot_done
		/usr/bin/recovery &

	;;
  stop)
		killall recovery
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
