################################################################################
#
# rktoolkit
#
################################################################################

RKTOOLKIT_VERSION = master
RKTOOLKIT_SITE = $(TOPDIR)/../external/rktoolkit
RKTOOLKIT_SITE_METHOD = local
RKTOOLKIT_LICENSE_FILES = LICENSE
RKTOOLKIT_LICENSE = Apache-2.0

RKTOOLKIT_CFLAGS = $(TARGET_CFLAGS)
ifeq ($(BR2_PACKAGE_RKTOOLKIT_STATIC),y)
RKTOOLKIT_CFLAGS += -static
endif

define RKTOOLKIT_BUILD_IO
	$(TARGET_CC) $(RKTOOLKIT_CFLAGS) $(TARGET_LDFLAGS) $(@D)/io.c \
		-o $(@D)/io
endef
RKTOOLKIT_POST_BUILD_HOOKS += RKTOOLKIT_BUILD_IO

define RKTOOLKIT_INSTALL_IO
	$(INSTALL) -D -m 755 $(@D)/io $(TARGET_DIR)/usr/bin/io
endef
RKTOOLKIT_POST_INSTALL_TARGET_HOOKS += RKTOOLKIT_INSTALL_IO

define RKTOOLKIT_BUILD_UPDATE
	$(TARGET_CC) $(RKTOOLKIT_CFLAGS) $(TARGET_LDFLAGS) $(@D)/update.c \
		$(@D)/update_recv/update_recv.c -I$(@D)/update_recv/ \
		-o $(@D)/update
endef
RKTOOLKIT_POST_BUILD_HOOKS += RKTOOLKIT_BUILD_UPDATE

define RKTOOLKIT_INSTALL_UPDATE
	$(INSTALL) -D -m 755 $(@D)/update $(TARGET_DIR)/usr/bin/update
endef
RKTOOLKIT_POST_INSTALL_TARGET_HOOKS += RKTOOLKIT_INSTALL_UPDATE

define RKTOOLKIT_BUILD_VENDOR_STORAGE
	$(TARGET_CC) $(RKTOOLKIT_CFLAGS) $(TARGET_LDFLAGS) \
		$(@D)/vendor_storage.c -o $(@D)/vendor_storage
endef
RKTOOLKIT_POST_BUILD_HOOKS += RKTOOLKIT_BUILD_VENDOR_STORAGE

define RKTOOLKIT_INSTALL_VENDOR_STORAGE
	$(INSTALL) -D -m 755 $(@D)/vendor_storage \
		$(TARGET_DIR)/usr/bin/vendor_storage
endef
RKTOOLKIT_POST_INSTALL_TARGET_HOOKS += RKTOOLKIT_INSTALL_VENDOR_STORAGE

RKTOOLKIT_VENDOR_STORAGE_LIB_NAME = libvendor_storage.so
RKTOOLKIT_VENDOR_STORAGE_INCLUDE_NAME = vendor_storage.h
define RKTOOLKIT_BUILD_VENDOR_STORAGE_LIB
	$(TARGET_CC) $(TARGET_CFLAGS) $(TARGET_LDFLAGS) $(@D)/vendor_storage.c -DBUILD_LIB_VENDOR_STORAGE -shared -fPIC -o $(@D)/$(RKTOOLKIT_VENDOR_STORAGE_LIB_NAME)
endef
RKTOOLKIT_POST_BUILD_HOOKS += RKTOOLKIT_BUILD_VENDOR_STORAGE_LIB

define RKTOOLKIT_INSTALL_LIB_TARGET_CMDS
	$(INSTALL) -D -m 755 $(@D)/$(RKTOOLKIT_VENDOR_STORAGE_LIB_NAME) $(TARGET_DIR)/usr/lib || true
	$(INSTALL) -D -m 755 $(@D)/$(RKTOOLKIT_VENDOR_STORAGE_INCLUDE_NAME) $(STAGING_DIR)/usr/include || true
	$(INSTALL) -D -m 755 $(@D)/$(RKTOOLKIT_VENDOR_STORAGE_LIB_NAME) $(STAGING_DIR)/usr/lib/ || true
endef
RKTOOLKIT_POST_INSTALL_TARGET_HOOKS += RKTOOLKIT_INSTALL_LIB_TARGET_CMDS

$(eval $(generic-package))
