#!/bin/sh
#
# Start linux weston...
#

# Load default env variables from profiles(e.g. /etc/profile.d/weston.sh)
. /etc/profile

case "$1" in
  start)
		printf "Starting weston: "

		weston&
	;;
  stop)
		killall weston
		printf "stop finished"
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
