CALLFUNIPC_SITE = $(TOPDIR)/../external/CallFunIpc
CALLFUNIPC_SITE_METHOD = local

CALLFUNIPC_INSTALL_STAGING = YES

CALLFUNIPC_DEPENDENCIES = libgdbus

ifeq ($(BR2_PACKAGE_CALLFUNIPC_DEMO),y)
CALLFUNIPC_CONF_OPTS += -DDEMO=ON
endif

$(eval $(cmake-package))
