RKWIFIBT_APP_SITE = $(TOPDIR)/../external/rkwifibt-app
RKWIFIBT_APP_SITE_METHOD = local
RKWIFIBT_APP_INSTALL_STAGING = YES

RKWIFIBT_APP_CONF_OPTS += -DBLUEZ5_UTILS=TRUE
RKWIFIBT_APP_CONF_OPTS += -DBLUEZ=TRUE
RKWIFIBT_APP_CONF_OPTS += -DREALTEK=TRUE
RKWIFIBT_APP_DEPENDENCIES += readline bluez5_utils libglib2

ifeq ($(call qstrip,$(BR2_ARCH)), arm)
RKWIFIBT_APP_BUILD_TYPE = arm
else ifeq ($(call qstrip, $(BR2_ARCH)), aarch64)
RKWIFIBT_APP_BUILD_TYPE = arm64
endif

RKWIFIBT_APP_CONF_OPTS += -DCPU_ARCH=$(BR2_ARCH) -DBUILD_TYPE=$(RKWIFIBT_APP_BUILD_TYPE)

RKWIFIBT_APP_DEPENDENCIES += wpa_supplicant alsa-lib

RKWIFIBT_APP_CONF_OPTS += -DCMAKE_INSTALL_STAGING=$(STAGING_DIR)

$(eval $(cmake-package))
